# Generated by Django 3.0.8 on 2020-08-10 10:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('client_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('CONNECTED', 'connected'), ('DISCONNECTED', 'disconnected')], default='disconnected', max_length=20)),
                ('type', models.CharField(blank=True, choices=[('RAVOP', 'ravop'), ('RAVJS', 'ravjs')], max_length=10, null=True)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disconnected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('scalar', 'scalar'), ('ndarray', 'ndarray')], max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'data',
            },
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'graph',
            },
        ),
        migrations.CreateModel(
            name='Op',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('node_type', models.CharField(choices=[('INPUT', 'input'), ('MIDDLE', 'middle'), ('OUTPUT', 'output')], max_length=100)),
                ('inputs', models.TextField(blank=True, null=True)),
                ('outputs', models.CharField(blank=True, max_length=300, null=True)),
                ('op_type', models.CharField(choices=[('UNARY', 'unary'), ('BINARY', 'binary'), ('OTHER', 'other')], max_length=100)),
                ('operator', models.CharField(choices=[('MATRIX_MULTIPLICATION', 'matrix_multiplication'), ('ADDITION', 'addition'), ('SUBTRACTION', 'subtraction'), ('ELEMENT_WISE_MULTIPLICATION', 'element_wise_multiplication'), ('DIVISION', 'division'), ('LINEAR', 'linear'), ('NEGATION', 'negation'), ('EXPONENTIAL', 'exponential'), ('TRANSPOSE', 'transpose'), ('NATURAL_LOG', 'natural_log')], max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('COMPUTING', 'computing'), ('COMPUTED', 'computed'), ('FAILED', 'failed')], default='pending', max_length=20)),
                ('client_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('graph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graphs', to='app.Graph')),
            ],
            options={
                'db_table': 'op',
            },
        ),
    ]
